-- MySQL Script generated by MySQL Workbench
-- 02/13/17 13:06:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JOBdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JOBdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JOBdb` DEFAULT CHARACTER SET utf8 ;
USE `JOBdb` ;

-- -----------------------------------------------------
-- Table `JOBdb`.`login_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`login_tb` (
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `user_type` INT NOT NULL DEFAULT 1,
  `acct_id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `user_name_UNIQUE` (`username` ASC),
  PRIMARY KEY (`acct_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`employee_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`employee_tb` (
  `emp_AI` INT NOT NULL AUTO_INCREMENT,
  `emp_id` VARCHAR(20) GENERATED ALWAYS AS (CONCAT('emp_',emp_AI)) VIRTUAL,
  `full_name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `position_type` INT NOT NULL,
  UNIQUE INDEX `emp_no_UNIQUE` (`emp_AI` ASC),
  PRIMARY KEY (`emp_AI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`inventory_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`inventory_tb` (
  `item_AI` INT NOT NULL,
  `item_id` VARCHAR(20) GENERATED ALWAYS AS (concat('item_',item_AI)) VIRTUAL,
  `item_name` VARCHAR(100) NOT NULL,
  `item_quantity` INT NOT NULL DEFAULT 0,
  `item_price` DECIMAL(13,2) NOT NULL,
  `critical_amount` INT NOT NULL DEFAULT 0,
  `added_by_emp_id` VARCHAR(20) NOT NULL,
  `supplier_id` VARCHAR(20) NOT NULL,
  `category_id` VARCHAR(20) NOT NULL,
  `part_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`item_AI`),
  UNIQUE INDEX `item_no_UNIQUE` (`item_AI` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`part_tb` (
  `part_AI` INT NOT NULL AUTO_INCREMENT,
  `part_id` VARCHAR(20) GENERATED ALWAYS AS (concat('part_',part_AI)) VIRTUAL,
  `part_name` VARCHAR(50) NOT NULL,
  `added_by_emp_id` VARCHAR(20) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`part_AI`),
  UNIQUE INDEX `part_AI_UNIQUE` (`part_AI` ASC),
  UNIQUE INDEX `part_name_UNIQUE` (`part_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`category_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`category_tb` (
  `category_AI` INT NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(20) GENERATED ALWAYS AS (concat('cat_',category_AI)) VIRTUAL,
  `category_name` VARCHAR(50) NOT NULL,
  `added_by_emp_id` VARCHAR(45) NOT NULL DEFAULT 'Default',
  UNIQUE INDEX `category_AI_UNIQUE` (`category_AI` ASC),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC),
  PRIMARY KEY (`category_AI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`supplier_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`supplier_tb` (
  `supplier_AI` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` VARCHAR(20) GENERATED ALWAYS AS (concat('supp_',supplier_AI)) VIRTUAL,
  `supplier_name` VARCHAR(100) NOT NULL,
  `added_by_emp_id` VARCHAR(20) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`supplier_AI`),
  UNIQUE INDEX `supplier_AI_UNIQUE` (`supplier_AI` ASC),
  UNIQUE INDEX `supplier_name_UNIQUE` (`supplier_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`user_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`user_type_tb` (
  `user_type` INT NOT NULL,
  `user_type_remark` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`user_type`),
  UNIQUE INDEX `emp_type_UNIQUE` (`user_type` ASC),
  UNIQUE INDEX `emp_desc_UNIQUE` (`user_type_remark` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`customer_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`customer_tb` (
  `customer_AI` INT NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(30) GENERATED ALWAYS AS (concat('cust_',customer_AI)) VIRTUAL,
  `customer_name` VARCHAR(100) NOT NULL,
  `customer_contact` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`customer_AI`),
  UNIQUE INDEX `customer_AI_UNIQUE` (`customer_AI` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`repair_job_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_job_tb` (
  `job_AI` INT NOT NULL AUTO_INCREMENT,
  `job_id` VARCHAR(50) GENERATED ALWAYS AS (concat('job_',job_AI)) VIRTUAL,
  `date_time_added` DATETIME NOT NULL,
  `customer_id` VARCHAR(30) NOT NULL,
  `job_type` INT NOT NULL,
  `total_price` DECIMAL(13,2) NOT NULL,
  `warranty_type` VARCHAR(30) NOT NULL DEFAULT 'warr_0',
  `warranty_remark` VARCHAR(45) NOT NULL DEFAULT 'No warranty',
  `watch_serial_no` VARCHAR(100) NOT NULL,
  `watch_kind` INT NOT NULL,
  `watch_build` INT NOT NULL,
  `watch_remark` VARCHAR(500) NOT NULL,
  `technician_id` VARCHAR(20) NULL,
  `repair_status_id` INT NULL DEFAULT 1,
  `start_repair_date` DATE NOT NULL,
  `expected_claim_date` DATE NULL,
  UNIQUE INDEX `job_AI_UNIQUE` (`job_AI` ASC),
  PRIMARY KEY (`job_AI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`temp_part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`temp_part_tb` (
  `item_id` VARCHAR(20) NOT NULL,
  `item_quantity` INT NOT NULL,
  `item_price` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`repair_part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_part_tb` (
  `job_id` VARCHAR(50) NOT NULL,
  `item_id` VARCHAR(20) NOT NULL,
  `item_quantity` INT NOT NULL,
  `item_price` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`watch_kind_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`watch_kind_tb` (
  `watch_kind` INT NOT NULL,
  `watch_kind_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`watch_kind`),
  UNIQUE INDEX `watch_kind_UNIQUE` (`watch_kind` ASC),
  UNIQUE INDEX `watch_kind_desc_UNIQUE` (`watch_kind_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`job_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`job_type_tb` (
  `job_type` INT NOT NULL AUTO_INCREMENT,
  `job_type_remark` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`job_type`),
  UNIQUE INDEX `job_type_UNIQUE` (`job_type` ASC),
  UNIQUE INDEX `job_type_desc_UNIQUE` (`job_type_remark` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`job_desc_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`job_desc_tb` (
  `job_desc_AI` INT NOT NULL AUTO_INCREMENT,
  `job_desc_id` VARCHAR(50) GENERATED ALWAYS AS (concat('job_desc_',job_desc_AI)) VIRTUAL,
  `job_desc` VARCHAR(300) NOT NULL,
  `job_desc_price` DECIMAL(13,2) NOT NULL,
  UNIQUE INDEX `job_desc_AI_UNIQUE` (`job_desc_AI` ASC),
  PRIMARY KEY (`job_desc_AI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`warranty_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`warranty_type_tb` (
  `warranty_AI` INT NOT NULL AUTO_INCREMENT,
  `warranty_type` VARCHAR(30) GENERATED ALWAYS AS (concat('warr_',warranty_AI)) VIRTUAL,
  `warranty_type_remark` VARCHAR(100) NOT NULL,
  `warranty_day` INT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE INDEX `warranty_AI_UNIQUE` (`warranty_AI` ASC),
  PRIMARY KEY (`warranty_AI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`temp_svc_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`temp_svc_tb` (
  `job_desc_id` VARCHAR(50) NOT NULL,
  `job_desc_price` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`job_desc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`position_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`position_type_tb` (
  `position_type` INT NOT NULL,
  `position_type_remark` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`position_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`repair_svc_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_svc_tb` (
  `job_desc_id` VARCHAR(50) NOT NULL,
  `job_desc_price` DECIMAL(13,2) NOT NULL,
  PRIMARY KEY (`job_desc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`repair_status_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_status_tb` (
  `repair_status_id` INT NOT NULL,
  `repair_status_remark` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`repair_status_id`),
  UNIQUE INDEX `repair_status_id_UNIQUE` (`repair_status_id` ASC),
  UNIQUE INDEX `repair_status_remark_UNIQUE` (`repair_status_remark` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`watch_build_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`watch_build_tb` (
  `watch_build` INT NOT NULL,
  `watch_build_remark` VARCHAR(70) NULL,
  PRIMARY KEY (`watch_build`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`warranty_job_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`warranty_job_tb` (
  `job_id` VARCHAR(50) NOT NULL,
  `warranty_expire` DATE NOT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `job_id_UNIQUE` (`job_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
