-- MySQL Script generated by MySQL Workbench
-- 02/03/17 15:05:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JOBdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JOBdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JOBdb` DEFAULT CHARACTER SET utf8 ;
USE `JOBdb` ;

-- -----------------------------------------------------
-- Table `JOBdb`.`repair_part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_part_tb` (
  `job_id` VARCHAR(50) NOT NULL,
  `item_id` VARCHAR(20) NOT NULL,
  `item_quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`inventory_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`inventory_tb` (
  `item_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` VARCHAR(20) GENERATED ALWAYS AS (concat('item_',item_AI)) STORED,
  `item_name` VARCHAR(100) NOT NULL,
  `item_quantity` INT NOT NULL DEFAULT 0,
  `critical_amount` INT NOT NULL DEFAULT 0,
  `added_by_emp_id` VARCHAR(20) NOT NULL,
  `supplier_id` VARCHAR(20) NOT NULL,
  `category_id` VARCHAR(20) NOT NULL,
  `part_id` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_no_UNIQUE` (`item_AI` ASC),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC),
  CONSTRAINT `fk_inventory_tb_repair_part_tb1`
    FOREIGN KEY (`item_id`)
    REFERENCES `JOBdb`.`repair_part_tb` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`supplier_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`supplier_tb` (
  `supplier_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_id` VARCHAR(20) GENERATED ALWAYS AS (concat('supp_',supplier_AI)) STORED,
  `supplier_name` VARCHAR(100) NOT NULL,
  `added_by_emp_id` VARCHAR(20) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`supplier_id`),
  UNIQUE INDEX `supplier_AI_UNIQUE` (`supplier_AI` ASC),
  UNIQUE INDEX `supplier_id_UNIQUE` (`supplier_id` ASC),
  UNIQUE INDEX `supplier_name_UNIQUE` (`supplier_name` ASC),
  CONSTRAINT `fk_supplier_tb_inventory_tb1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `JOBdb`.`inventory_tb` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`part_tb` (
  `part_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `part_id` VARCHAR(20) GENERATED ALWAYS AS (concat('part_',part_AI)) STORED,
  `part_name` VARCHAR(50) NOT NULL,
  `added_by_emp_id` VARCHAR(20) NOT NULL DEFAULT 'Default',
  PRIMARY KEY (`part_id`),
  UNIQUE INDEX `part_id_UNIQUE` (`part_id` ASC),
  UNIQUE INDEX `part_AI_UNIQUE` (`part_AI` ASC),
  UNIQUE INDEX `part_name_UNIQUE` (`part_name` ASC),
  CONSTRAINT `fk_part_tb_inventory_tb1`
    FOREIGN KEY (`part_id`)
    REFERENCES `JOBdb`.`inventory_tb` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`category_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`category_tb` (
  `category_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(20) GENERATED ALWAYS AS (concat('cat_',category_AI)) STORED,
  `category_name` VARCHAR(50) NOT NULL,
  `added_by_emp_id` VARCHAR(45) NOT NULL DEFAULT 'Default',
  UNIQUE INDEX `category_AI_UNIQUE` (`category_AI` ASC),
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC),
  UNIQUE INDEX `category_name_UNIQUE` (`category_name` ASC),
  CONSTRAINT `fk_category_tb_inventory_tb1`
    FOREIGN KEY (`category_id`)
    REFERENCES `JOBdb`.`inventory_tb` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`technician_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`technician_tb` (
  `emp_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` VARCHAR(20) GENERATED ALWAYS AS (CONCAT('emp_',emp_AI)) STORED,
  `full_name` VARCHAR(100) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  UNIQUE INDEX `emp_no_UNIQUE` (`emp_AI` ASC),
  PRIMARY KEY (`emp_id`),
  UNIQUE INDEX `emp_id_UNIQUE` (`emp_id` ASC),
  CONSTRAINT `fk_technician_tb_supplier_tb1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `JOBdb`.`supplier_tb` (`added_by_emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_tb_part_tb1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `JOBdb`.`part_tb` (`added_by_emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_tb_category_tb1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `JOBdb`.`category_tb` (`added_by_emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_technician_tb_inventory_tb1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `JOBdb`.`inventory_tb` (`added_by_emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`login_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`login_tb` (
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `user_type` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `user_name_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_login_tb_technician_tb`
    FOREIGN KEY (`username`)
    REFERENCES `JOBdb`.`technician_tb` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`user_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`user_type_tb` (
  `user_type` INT UNSIGNED NOT NULL,
  `user_desc` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`user_type`),
  UNIQUE INDEX `emp_type_UNIQUE` (`user_type` ASC),
  UNIQUE INDEX `emp_desc_UNIQUE` (`user_desc` ASC),
  CONSTRAINT `fk_user_type_tb_login_tb1`
    FOREIGN KEY (`user_type`)
    REFERENCES `JOBdb`.`login_tb` (`user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`customer_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`customer_tb` (
  `customer_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(30) GENERATED ALWAYS AS (concat('cust_',customer_AI)) STORED,
  `customer_name` VARCHAR(100) NOT NULL,
  `customer_contact` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_AI_UNIQUE` (`customer_AI` ASC),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`claim_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`claim_tb` (
  `claim_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `claim_id` VARCHAR(60) GENERATED ALWAYS AS (concat('claim_id_',claim_AI)) STORED,
  `job_id` VARCHAR(45) NOT NULL,
  `start_repair` DATE NOT NULL,
  `expected_claim` DATE NULL,
  UNIQUE INDEX `claim_id_UNIQUE` (`claim_id` ASC),
  UNIQUE INDEX `claim_AI_UNIQUE` (`claim_AI` ASC),
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`job_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`job_type_tb` (
  `job_type` INT UNSIGNED NOT NULL,
  `job_type_desc` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`job_type`),
  UNIQUE INDEX `job_type_UNIQUE` (`job_type` ASC),
  UNIQUE INDEX `job_type_desc_UNIQUE` (`job_type_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`job_desc_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`job_desc_tb` (
  `job_desc_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_desc_type` VARCHAR(50) GENERATED ALWAYS AS (concat('job_desc_',job_desc_AI)) VIRTUAL,
  `job_desc` VARCHAR(300) NOT NULL,
  UNIQUE INDEX `job_desc_AI_UNIQUE` (`job_desc_AI` ASC),
  PRIMARY KEY (`job_desc_type`),
  UNIQUE INDEX `job_desc_type_UNIQUE` (`job_desc_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`warranty_type_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`warranty_type_tb` (
  `warranty_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `warranty_type` VARCHAR(30) GENERATED ALWAYS AS (concat('warr_',warranty_AI)) STORED,
  `warranty_desc` VARCHAR(100) NOT NULL,
  `warranty_day` INT UNSIGNED NOT NULL DEFAULT 0,
  UNIQUE INDEX `warranty_AI_UNIQUE` (`warranty_AI` ASC),
  PRIMARY KEY (`warranty_type`),
  UNIQUE INDEX `warranty_type_UNIQUE` (`warranty_type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`watch_kind_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`watch_kind_tb` (
  `watch_kind` INT UNSIGNED NOT NULL,
  `watch_kind_desc` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`watch_kind`),
  UNIQUE INDEX `watch_kind_UNIQUE` (`watch_kind` ASC),
  UNIQUE INDEX `watch_kind_desc_UNIQUE` (`watch_kind_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`repair_job_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`repair_job_tb` (
  `job_AI` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` VARCHAR(50) GENERATED ALWAYS AS (concat('job_',job_AI)) STORED,
  `customer_id` VARCHAR(30) NOT NULL,
  `job_type` INT UNSIGNED NOT NULL,
  `job_desc_type` VARCHAR(50) NOT NULL,
  `warranty_type` VARCHAR(30) NOT NULL DEFAULT 'warr_0',
  `warranty_remark` VARCHAR(45) NOT NULL DEFAULT 'No warranty',
  `watch_serial_no` VARCHAR(100) NOT NULL,
  `watch_kind` INT NOT NULL,
  `watch_remark` VARCHAR(500) NOT NULL,
  `technician_id` VARCHAR(20) NULL,
  PRIMARY KEY (`job_id`),
  UNIQUE INDEX `job_AI_UNIQUE` (`job_AI` ASC),
  UNIQUE INDEX `job_id_UNIQUE` (`job_id` ASC),
  INDEX `fk_repair_job_tb_job_type_tb1_idx` (`job_type` ASC),
  INDEX `fk_repair_job_tb_job_desc_tb1_idx` (`job_desc_type` ASC),
  INDEX `fk_repair_job_tb_warranty_type_tb1_idx` (`warranty_type` ASC),
  INDEX `fk_repair_job_tb_watch_kind_tb1_idx` (`watch_kind` ASC),
  INDEX `fk_repair_job_tb_technician_tb1_idx` (`technician_id` ASC),
  INDEX `fk_repair_job_tb_customer_tb1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_repair_job_tb_claim_tb1`
    FOREIGN KEY (`job_id`)
    REFERENCES `JOBdb`.`claim_tb` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_job_type_tb1`
    FOREIGN KEY (`job_type`)
    REFERENCES `JOBdb`.`job_type_tb` (`job_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_job_desc_tb1`
    FOREIGN KEY (`job_desc_type`)
    REFERENCES `JOBdb`.`job_desc_tb` (`job_desc_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_warranty_type_tb1`
    FOREIGN KEY (`warranty_type`)
    REFERENCES `JOBdb`.`warranty_type_tb` (`warranty_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_watch_kind_tb1`
    FOREIGN KEY (`watch_kind`)
    REFERENCES `JOBdb`.`watch_kind_tb` (`watch_kind`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_technician_tb1`
    FOREIGN KEY (`technician_id`)
    REFERENCES `JOBdb`.`technician_tb` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_customer_tb1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `JOBdb`.`customer_tb` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repair_job_tb_repair_part_tb1`
    FOREIGN KEY (`job_id`)
    REFERENCES `JOBdb`.`repair_part_tb` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JOBdb`.`temp_part_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JOBdb`.`temp_part_tb` (
  `item_id` VARCHAR(20) NOT NULL,
  `item_quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC),
  CONSTRAINT `fk_temp_part_tb_inventory_tb1`
    FOREIGN KEY (`item_id`)
    REFERENCES `JOBdb`.`inventory_tb` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
